<?php

namespace App\Repository\Business;

use App\Entity\Business\Url;
use App\Repository\AbstractFoundationRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends AbstractFoundationRepository
{
    /**
     * UrlRepository constructor.
     * @param \Doctrine\Persistence\ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Url::class);
    }
}
