<?php

namespace App\Repository\User;

use App\Entity\User\ActorRoleAuthorization;
use App\Repository\AbstractRoleAuthorizationRepository;
use App\Repository\RoleAuthorizationRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ActorRoleAuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRoleAuthorizationRepository extends AbstractRoleAuthorizationRepository
{
    /** @var string $mainTable table principal contenant les roles */
    protected $mainTable = 'app_user_actor_role_authorization';
    /** @var string $secondaryTable table contenant les utilisateurs ayant un role */
    protected $secondaryTable = 'app_user_actor_role';

    /**
     * ActorRoleAuthorizationRepository constructor.
     * @param \Doctrine\Persistence\ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ActorRoleAuthorization::class);
    }
}
