<?php

namespace App\Repository\User;

use App\Entity\User\ActorRole;
use App\Repository\AbstractRoleRepository;
use DateTime;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ActorRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRoleRepository extends AbstractRoleRepository
{
    /**
     * ActorRoleRepository constructor.
     * @param \Doctrine\Persistence\ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ActorRole::class);
    }

    /**
     * Retrieve entities for pagination
     *
     * @param int $numberPerPage
     * @param int $page
     * @param int $company_id
     * @param string $query
     * @param $fromDate
     * @param $toDate
     * @param mixed ...$args
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     * @throws \Exception
     */
    public function retrieve(int $numberPerPage = null, int $page = null, string $query = null, \DateTime $fromDate = null, \DateTime $toDate = null, ...$args)
    {
        $qb = $this->createQueryBuilder('entity')
            ->select('entity');
        $qb->where('entity.deleted = 0');

        if (strlen(trim($query))) {
            $qb->andWhere($qb->expr()->like('entity.name', $qb->expr()->literal('%' . $query . '%')))
                ->orWhere($qb->expr()->like('entity.description', $qb->expr()->literal('%' . $query . '%')));
        }
        if ($fromDate && $fromDate instanceof DateTime) {
            $qb->andWhere('entity.dateAdd >= :fromDate');
        }
        if ($toDate && $toDate instanceof DateTime) {
            $qb->andWhere('entity.dateAdd <= :toDate');
        }
        if ($fromDate && $fromDate instanceof DateTime)
            $qb->setParameter('fromDate', new DateTime($fromDate->format('Y-m-d') . " 00:00:00"));
        if ($toDate && $toDate instanceof DateTime)
            $qb->setParameter('toDate', new DateTime($toDate->format('Y-m-d') . ' 23:59:59'));

        $qb->orderBy('entity.dateAdd', 'DESC');
        $query = $qb->getQuery();
        $query->setFirstResult(($page - 1) * $numberPerPage)
            ->setMaxResults($numberPerPage);

        return new Paginator($query);
    }
}
