<?php

namespace App\Repository\User;

use App\Entity\User\ActorMember;
use App\Repository\AbstractMemberRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ActorMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorMemberRepository extends AbstractMemberRepository
{
    /**
     * ActorMemberRepository constructor.
     * @param \Doctrine\Persistence\ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ActorMember::class);
    }
}
