<?php

namespace App\Repository\User;

use App\Entity\User\Guest;
use App\Repository\AbstractFoundationRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * GuestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestRepository extends AbstractFoundationRepository
{
    /**
     * GuestRepository constructor.
     * @param \Doctrine\Persistence\ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Guest::class);
    }
}
